language: node_js
node_js:
- '12'
env:
  global:
  - MATTERMOST_CHANNEL=publication
  # REGISTRY_TOKEN(editor=cozy, app=wanimo)
  - secure: Ds2EDZ4LKlRIX5mujD9eF6/LYO2CQPSQbZFQ4JPH1fl30Dqf7wqFM2XOZdQC6HlAhxu4z1ZL7IJg4tC7TsUgdgOYKryzAKbqMdMiJRRPcZUq6YPynAV1UKXzw8MM1MaMNa/NZDsBM+ej/V4v1f4ruvckn4fxA99YLgn4nrtszgbqVqRMYdNbHmQo9zMryGVXdosaP0vX7WSWGPU1x6odOCa2yVf3oiXhnJijy0TFWBYxYQpbs57Yx2K7xq+GF+RNhlk2lrMOTRdIK4DDvXP17O1BxVO1hrejevl9dSJ6+bz2psPPi6uFEg0m4dMkaFW/0hrDlur3nvYjo2KZW04PD+GaxgrhCEUvsw5G5uC+FlVuUQmDAJxzrdnqZl/llA+y8FixRCs4JOdBui1LwDqolpne94Md5h1rWSbCgeRaXZLBbjmFWPKOTTNi2da57T/zP7tvEJx8Cem5aQ9XDlo30jjCSErgua3Hvh2OR8dxPcccXo6i92evXF7rPRjrUjoKv2WmCbsNK7JEnfSV5L6Vr9+kVQpR0xwO1eS7IfaJqS7JHkwMpQ28KrxIgaYouOxOPuA4/8oU+KbUTYHtwo61S1Q8pxDGXXnlnaG35T7qU4WRl7lDBKLalhvtwRoUdyNsftunvlxlASWpnzSGX4jClydcPc2DLx60bjvQal7GZSY=
  # MATTERMOST_HOOK_URL
  - secure: Mrxmme2xiwKD5zrTn50FDuBirvpPkC9Y3qs6Z+pnKEARqvnG9z4XrnYR7JaQl63qhm63XA7jjYASKGBQxR9x+jCkKhswzfg1BTYBUbmB7K7DSJ7e94xTbYPh9G47DXY8IugZiPak4SEfHEf3q2Y/+OqSDsyq/ijVLEOokTNaDWIgSiWfen5VzG547T1BAWltKyEkGH6Ls02sAQvpjNtJlF7apLiS/vWSSXPqPUg/+2AcJ+bmekH8TzxwG5PPlq6N/tZFFE0xS1epWmsNz8DMG1/RaYaF0r21RHKdE+16/LXT8vtZdBNifOLrcvIa6S2J9ctRUa3Nl5MgiZxfw0SyD9Tkb1tndTPDKScitIl1HD5KYZDPLFcioeyu/JYTRepi0vq83ub3BZDiyDslgNt5WsfhEjDUhkbm+TujL0E8QLmCriD9h9dbbLrUkr8lJwcnyD6tuFfeQWu6hSZSY7nlV5nx1utfuTboUVvWjH3+Si97XfS+cto20IelnjDXisIEVRTg92rUqQluSFYOw0eKUeqXgaQBgSJEmCXqXjh9jvfUcnOFVnmbycAKQzGqCTFXFkhxEeBv+/rOEA772KYXiFzQJfjO/GuTG0QdGO2OORIIuwZ0uOLo2Q1u78R8ULrYKmGckH88AP4ooLzOD738+4c0M/jSeOoW+/mcG6rYK8Y=
cache:
  yarn: true
  directories:
  - node_modules
branches:
  except:
  - build
  - build-debug
script:
- yarn lint
- yarn build
deploy:
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
  on:
    branch: master
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish --postpublish mattermost
  on:
    tags: true
before_install:
- openssl aes-256-cbc -K $encrypted_88e6b096c805_key -iv $encrypted_88e6b096c805_iv
  -in github_deploy_key.enc -out /tmp/github_deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/github_deploy_key
- ssh-add /tmp/github_deploy_key
after_deploy:
- rm /tmp/github_deploy_key
- ssh-add -D
